version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: clo835-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clo835_db
      MYSQL_USER: clo835_user
      MYSQL_PASSWORD: clo835_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - clo835-network

  app:
    build: .
    container_name: clo835-app
    ports:
      - "81:8080"
    environment:
      - DB_HOST=mysql
      - DB_NAME=clo835_db
      - DB_USER=root
      - DB_PASSWORD=password
      - STUDENT_NAME="Amardeep Puri, Bibek Pandey, Suraaj Vashisht"
      - BACKGROUND_IMAGE_URL=https://clo835-finalproject-group9.s3.us-east-1.amazonaws.com/background.jpg
      - S3_BUCKET=clo835-finalproject-group9
      - S3_IMAGE_KEY=background.jpg
    networks:
      - clo835-network
    volumes:
      - ./app:/app
      - /app/static/images

volumes:
  mysql_data:

networks:
  clo835-network:
    driver: bridge 
