apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  BACKGROUND_IMAGE_URL: "https://clo835-finalproject-group9.s3.us-east-1.amazonaws.com/background.jpg"
  STUDENT_NAME: "Amardeep Puri, Bibek Pandey, Suraaj Vashisht"
  S3_BUCKET: "clo835-finalproject-group9"
  S3_IMAGE_KEY: "background.jpg"
  DB_NAME: "clo835_db"
